import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex md:flex-row flex-col gap-y-2 gap-x-4 justify-center py-20 mx-auto max-w-2xl">
          <Link
            href="/"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            Home
          </Link>
          <Link
            href="/server-action"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            Server Action
          </Link>
          <Link
            href="/use-form-state"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            useFormState
          </Link>
          {/* <Link
            href="/react-hook-form"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            React Hook Form B 
          </Link> */}

          <Link
            href="/react-hook-form-b"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            React Hook Form B
          </Link>
          <Link
            href="/min-use-action-state"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            Minimal useActionState
          </Link>
          <Link
            href="/expand-use-action-state"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            Expanded useActionState
          </Link>
        </nav>
        <main className="mx-auto max-w-2xl">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
